In [1]:
import  numpy as np

In [3]:
# Creating Array 
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [6]:
arr1 = np.arange(9).reshape((3,3))

In [7]:
print(arr)
print(arr1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
# Getting the shape of the array
arr.shape

(3, 3)

In [9]:
# Getting the number of rows of the array
arr.shape[0]

3

In [10]:
# Getting the number of column of the array
arr.shape[1]

3

In [11]:
# Getting the dimension of the array
arr.ndim

2

In [14]:
# Getting the datatype of the array
arr.dtype

dtype('int32')

In [16]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [17]:
np.square(arr)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]], dtype=int32)

In [18]:
np.add(arr,arr1)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

In [19]:
np.multiply(arr,arr1)

array([[ 0,  2,  6],
       [12, 20, 30],
       [42, 56, 72]])

In [22]:
np.divide(arr1,arr)

array([[0.        , 0.5       , 0.66666667],
       [0.75      , 0.8       , 0.83333333],
       [0.85714286, 0.875     , 0.88888889]])

In [25]:
np.exp(arr)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [26]:
np.log(arr)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [27]:
arr.std()

2.581988897471611

In [28]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
arr.var()

6.666666666666667